Injected kubeconfig is now writable
Secret volumes are read-only and operations such as

```terminal
kubectl config set-context --current --namespace=foo
error: open /mnt/.kube/config.lock: read-only file system
```

fail. To workaround it, an Init container copies the kubeconfig to an
empty volume which is used by the main terminal container.